### ISSUE TITLE
V1 deprecation

### ISSUE THREAD

**Issue by jemshit** [WalletConnect/WalletConnectSwift#143]
Hi, 
As you may know, WalletConnect decided to shutdown bridge servers for V1 on March 2023.
Will gnosis's v1 (https://safe-walletconnect.gnosis.io) server keep running after that date?

**Comment by jemshit** [comment]
@DmitryBespalov

**Comment by DmitryBespalov** [comment]
Good day, please migrate from that server to safe-walletconnect.safe.global

Wallet Connect wants to facilitate migration to v2 next year, that's why they're shutting down.

I expect that the wallets should migrate to v2 until March 2023, so I can't say for sure if the v1 service will still run. 

In any case, those servers were spun off out of performance reasons, and there's no public service agreement or commitment from Gnosis or Safe for these services, i.e. they are used internally for the Safe app, however I know that several dapps and wallets also use the same server.

If you want to make sure that the v1 server is running after March 2023, please run your own server - all of the code is open source and should be possible to self-host 😉
